services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: api
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true